//
// Created by aml on 22/05/2026.
//

#ifndef LISTASIMPLEMENTEENLAZADA_MISFUNCIONES_H
#define LISTASIMPLEMENTEENLAZADA_MISFUNCIONES_H

void ordenarLista(Lista &listaRobot);

#endif //LISTASIMPLEMENTEENLAZADA_MISFUNCIONES_H